# -*- coding: utf-8 -*-
"""Customer_Purchase_Behavior_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lXtO-wyBjilh_CC4U-LsadaytLdorxx
"""

# ==========================================
# 1. Imports & Setup
# ==========================================
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/content/sales_data_cleaned.csv")

# ==========================================
# 2. Data Loading & Inspection
# ==========================================
df.head()

df.info()
df.shape
df.isnull().sum()

df.duplicated().sum()

df.describe()

# ==========================================
# 3. Exploratory Data Analysis & Visuals
# ==========================================
Regional_Sales = (
    df.groupby("Region")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print(Regional_Sales)

# Chart 1: Total Sales by Region
Regional_Sales.plot(kind="bar")

plt.title("Regional Sales")
plt.xlabel("Region")
plt.ylabel("Sales")

plt.show()

# Chart 2: Distribution of Sales
plt.hist(df["Sales"])

plt.title("Distribution of Sales")
plt.xlabel("Sales")
plt.ylabel("Frequency")

plt.show()

# Chart 3: Sales vs. Profit
plt.scatter(df["Sales"], df["Profit"])

plt.title("Sales vs Profit")
plt.xlabel("Sales")
plt.ylabel("Profit")

plt.show()